In [1]:
import numpy as np
from efficient_probit_regression.sampling import calculate_lewis_weights_exact, calculate_l2_lp_leverage_score, to_density

# 1. Laden der notwendigen Datensätze
%store -r Iris
%store -r Webspam
%store -r KDDCup
%store -r Covertype
%store -r Example2D

print("Bestimmung von c = max(np.maximum(lewis_prob / l2_lp_prob, l2_lp_prob / lewis_prob))")
print("")

#Untersuchung für unterschiedliche Werte von p
p = [1.0, 1.3, 1.5, 1.7, 2.0]
rows_c = [] # hier sammeln wir alle Ergebnisse (dataset, p, c)

for i in p:
    print("p = ", i)
    print("")

    #Iris Datensatz
    print("Iris Datensatz")
    Iris_lewis_weights = calculate_lewis_weights_exact(Iris.X, p=i, T=20)
    Iris_lewis_prob = to_density(Iris_lewis_weights)
    Iris_l2_lp_scores = calculate_l2_lp_leverage_score(Iris.X, p=i)[0]
    Iris_l2_lp_prob = calculate_l2_lp_leverage_score(Iris.X, p=i)[1]
    Iris_c = max(np.maximum(Iris_lewis_prob / Iris_l2_lp_prob, Iris_l2_lp_prob / Iris_lewis_prob))
    print("Iris_c:", Iris_c)
    rows_c.append({
        "dataset": "Iris",
        "p": float(i),
        "c": float(Iris_c),
    })
    print("")

    #Example2D Datensatz
    print("Example2D Datensatz")
    Example2D_lewis_weights = calculate_lewis_weights_exact(Example2D.X, p=i, T=20)
    Example2D_lewis_prob = to_density(Example2D_lewis_weights)
    Example2D_l2_lp_scores = calculate_l2_lp_leverage_score(Example2D.X, p=i)[0]
    Example2D_l2_lp_prob = calculate_l2_lp_leverage_score(Example2D.X, p=i)[1]
    Example2D_c = max(np.maximum(Example2D_lewis_prob / Example2D_l2_lp_prob, Example2D_l2_lp_prob / Example2D_lewis_prob))
    print("Example2D_c:", Example2D_c)
    rows_c.append({
        "dataset": "Example2D",
        "p": float(i),
        "c": float(Example2D_c),
    })
    print("")

    #KDDCup Datensatz
    print("KDDCup Datensatz")
    KDDCup_lewis_weights = calculate_lewis_weights_exact(KDDCup.X, p=i, T=20)
    KDDCup_lewis_prob = to_density(KDDCup_lewis_weights)
    KDDCup_l2_lp_scores = calculate_l2_lp_leverage_score(KDDCup.X, p=i)[0]
    KDDCup_l2_lp_prob = calculate_l2_lp_leverage_score(KDDCup.X, p=i)[1]
    KDDCup_c = max(np.maximum(KDDCup_lewis_prob / KDDCup_l2_lp_prob, KDDCup_l2_lp_prob / KDDCup_lewis_prob))
    print("KDDCup_c:", KDDCup_c)
    rows_c.append({
        "dataset": "KDDCup",
        "p": float(i),
        "c": float(KDDCup_c),
    })
    print("")

    #Covertype Datensatz
    print("Covertype Datensatz")
    Covertype_lewis_weights = calculate_lewis_weights_exact(Covertype.X, p=i, T=20)
    Covertype_lewis_prob = to_density(Covertype_lewis_weights)
    Covertype_l2_lp_scores = calculate_l2_lp_leverage_score(Covertype.X, p=i)[0]
    Covertype_l2_lp_prob = calculate_l2_lp_leverage_score(Covertype.X, p=i)[1]
    Covertype_c = max(np.maximum(Covertype_lewis_prob / Covertype_l2_lp_prob, Covertype_l2_lp_prob / Covertype_lewis_prob))
    print("Covertype_c:", Covertype_c)
    rows_c.append({
        "dataset": "Covertype",
        "p": float(i),
        "c": float(Covertype_c),
    })
    print("")

    #Webspam Datensatz
    print("Webspam Datensatz")
    Webspam_lewis_weights = calculate_lewis_weights_exact(Webspam.X, p=i, T=20)
    Webspam_lewis_prob = to_density(Webspam_lewis_weights)
    Webspam_l2_lp_scores = calculate_l2_lp_leverage_score(Webspam.X, p=i)[0]
    Webspam_l2_lp_prob = calculate_l2_lp_leverage_score(Webspam.X, p=i)[1]
    Webspam_c = max(np.maximum(Webspam_lewis_prob / Webspam_l2_lp_prob, Webspam_l2_lp_prob / Webspam_lewis_prob))
    print("Webspam_c:", Webspam_c)
    rows_c.append({
        "dataset": "Webspam",
        "p": float(i),
        "c": float(Webspam_c),
    })
    print("")

Bestimmung von c = max(np.maximum(lewis_prob / l2_lp_prob, l2_lp_prob / lewis_prob))

p =  1.0

Iris Datensatz
Iris_c: 1.6017254866344897

Example2D Datensatz
Example2D_c: 1.6464655693646892

KDDCup Datensatz
KDDCup_c: 4.953569465538135

Covertype Datensatz
Covertype_c: 106.08083048232831

Webspam Datensatz
Webspam_c: 7.471362875415986

p =  1.3

Iris Datensatz
Iris_c: 1.6789190092250794

Example2D Datensatz
Example2D_c: 1.4790774874089234

KDDCup Datensatz
KDDCup_c: 4.016113190970496

Covertype Datensatz
Covertype_c: 57.036042921878725

Webspam Datensatz
Webspam_c: 6.251700302411295

p =  1.5

Iris Datensatz
Iris_c: 1.416014955378252

Example2D Datensatz
Example2D_c: 1.3114256978328724

KDDCup Datensatz
KDDCup_c: 3.013309051434195

Covertype Datensatz
Covertype_c: 150.70319736206923

Webspam Datensatz
Webspam_c: 4.092217130021129

p =  1.7

Iris Datensatz
Iris_c: 1.220227103305643

Example2D Datensatz
Example2D_c: 1.1974813021411537

KDDCup Datensatz
KDDCup_c: 2.0847426105031426

Covertype Datensatz
Covertype_c: 66.46219731743084

Webspam Datensatz
Webspam_c: 2.392403688855031

p =  2.0

Iris Datensatz
Iris_c: 1.0

Example2D Datensatz
Example2D_c: 1.0

KDDCup Datensatz
KDDCup_c: 1.0

Covertype Datensatz
Covertype_c: 1.043244879972065

Webspam Datensatz
Webspam_c: 1.0000047135608583

In [2]:
import pandas as pd

df_c = pd.DataFrame(rows_c)
df_c["c"] = df_c["c"].round(4)
df_c = df_c.sort_values(["dataset", "p"]).reset_index(drop=True)
display(df_c)

# als CSV speichern
out_csv = "Tabellen/Bestimmung_c.csv"
df_c.to_csv(out_csv, index=False)
print(f"CSV gespeichert: {out_csv}")

      dataset    p         c
0   Covertype  1.0  106.0808
1   Covertype  1.3   57.0360
2   Covertype  1.5  150.7032
3   Covertype  1.7   66.4622
4   Covertype  2.0    1.0432
5   Example2D  1.0    1.6465
6   Example2D  1.3    1.4791
7   Example2D  1.5    1.3114
8   Example2D  1.7    1.1975
9   Example2D  2.0    1.0000
10       Iris  1.0    1.6017
11       Iris  1.3    1.6789
12       Iris  1.5    1.4160
13       Iris  1.7    1.2202
14       Iris  2.0    1.0000
15     KDDCup  1.0    4.9536
16     KDDCup  1.3    4.0161
17     KDDCup  1.5    3.0133
18     KDDCup  1.7    2.0847
19     KDDCup  2.0    1.0000
20    Webspam  1.0    7.4714
21    Webspam  1.3    6.2517
22    Webspam  1.5    4.0922
23    Webspam  1.7    2.3924
24    Webspam  2.0    1.0000

CSV gespeichert: Tabellen/Bestimmung_c.csv

In [4]:
import numpy as np
import pandas as pd
from efficient_probit_regression.sampling import calculate_lewis_weights_exact, compute_leverage_scores, to_density

# Laden der notwendigen Datensätze
%store -r Iris
%store -r Webspam
%store -r KDDCup
%store -r Covertype
%store -r Example2D

print("Vergleich von min(l_ip, l_i2) * 0.5 <= w_i <= max(l_ip, l_i2) * 2:")
print("")

p = [1.0, 1.3, 1.5, 1.7, 2.0]
rows_cmp = []

datasets = {
    "Iris": Iris,
    "Example2D": Example2D,
    "Webspam": Webspam,
    "Covertype": Covertype,
    "KDDCup": KDDCup,
}

def process_dataset(dataset_name, X, p_val, rows_cmp, T=20):
    print(f"{dataset_name} Datensatz")
    print("")

    # l2 und lp leverage scores + Dichten
    l2_scores = compute_leverage_scores(X, p=2.0)
    l2_prob = to_density(l2_scores)

    lp_scores = compute_leverage_scores(X, p=p_val)
    lp_prob = to_density(lp_scores)

    # Lewis weights + Dichte
    lewis_weights = calculate_lewis_weights_exact(X, p=p_val, T=T)
    lewis_prob = to_density(lewis_weights)

    # Vergleich von Scores
    print("Vergleich von Scores")
    min_scores = np.minimum(lp_scores, l2_scores)
    max_scores = np.maximum(lp_scores, l2_scores)
    compare_scores = (lewis_weights >= min_scores * 0.5) & (lewis_weights <= max_scores * 2)

    print("Anzahl von TRUE:", int(np.sum(compare_scores)),
          "Anzahl von FALSE:", int(len(compare_scores) - np.sum(compare_scores)))
    print(round(np.sum(compare_scores) / len(compare_scores), 4) * 100, "% der Werte sind TRUE")
    print("")

    # Vergleich von normierten Verteilungen
    print("Vergleich von normierten Verteilungen")
    min_prob = np.minimum(lp_prob, l2_prob)
    max_prob = np.maximum(lp_prob, l2_prob)
    compare_prob = (lewis_prob >= min_prob * 0.5) & (lewis_prob <= max_prob * 2)

    print("Anzahl von TRUE:", int(np.sum(compare_prob)),
          "Anzahl von FALSE:", int(len(compare_prob) - np.sum(compare_prob)))
    print(round(np.sum(compare_prob) / len(compare_prob), 4) * 100, "% der Werte sind TRUE")
    print("")

    # ---- Speichern ----
    n = len(compare_scores)

    true_scores = int(np.sum(compare_scores))
    false_scores = int(n - true_scores)
    ratio_true_scores = true_scores / n

    true_prob = int(np.sum(compare_prob))
    false_prob = int(n - true_prob)
    ratio_true_prob = true_prob / n

    rows_cmp.append({
        "dataset": dataset_name,
        "p": float(p_val),
        "n": int(n),
        "true_scores": true_scores,
        "false_scores": false_scores,
        "ratio_true_scores": ratio_true_scores,
        "true_prob": true_prob,
        "false_prob": false_prob,
        "ratio_true_prob": ratio_true_prob,
    })

for p_val in p:
    print("p = ", p_val)
    print("")
    for dataset_name, ds in datasets.items():
        process_dataset(dataset_name, ds.X, p_val, rows_cmp, T=20)

Vergleich von min(l_ip, l_i2) * 0.5 <= w_i <= max(l_ip, l_i2) * 2:

p =  1.0

Iris Datensatz

Vergleich von Scores
Anzahl von TRUE: 150 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 150 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Example2D Datensatz

Vergleich von Scores
Anzahl von TRUE: 175 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 175 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Webspam Datensatz

Vergleich von Scores
Anzahl von TRUE: 349659 Anzahl von FALSE: 341
99.9 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 349669 Anzahl von FALSE: 331
99.91 % der Werte sind TRUE

Covertype Datensatz

Vergleich von Scores
Anzahl von TRUE: 580997 Anzahl von FALSE: 15
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 580996 Anzahl von FALSE: 16
100.0 % der Werte sind TRUE

KDDCup Datensatz

Vergleich von Scores
Anzahl von TRUE: 466227 Anzahl von FALSE: 27794
94.37 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 493964 Anzahl von FALSE: 57
99.99 % der Werte sind TRUE

p =  1.3

Iris Datensatz

Vergleich von Scores
Anzahl von TRUE: 150 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 150 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Example2D Datensatz

Vergleich von Scores
Anzahl von TRUE: 175 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 175 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Webspam Datensatz

Vergleich von Scores
Anzahl von TRUE: 338168 Anzahl von FALSE: 11832
96.61999999999999 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 349891 Anzahl von FALSE: 109
99.97 % der Werte sind TRUE

Covertype Datensatz

Vergleich von Scores
Anzahl von TRUE: 581001 Anzahl von FALSE: 11
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 581001 Anzahl von FALSE: 11
100.0 % der Werte sind TRUE

KDDCup Datensatz

Vergleich von Scores
Anzahl von TRUE: 478208 Anzahl von FALSE: 15813
96.8 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 493787 Anzahl von FALSE: 234
99.95 % der Werte sind TRUE

p =  1.5

Iris Datensatz

Vergleich von Scores
Anzahl von TRUE: 150 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 150 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Example2D Datensatz

Vergleich von Scores
Anzahl von TRUE: 175 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 175 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Webspam Datensatz

Vergleich von Scores
Anzahl von TRUE: 349741 Anzahl von FALSE: 259
99.92999999999999 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 349851 Anzahl von FALSE: 149
99.96000000000001 % der Werte sind TRUE

Covertype Datensatz

Vergleich von Scores
Anzahl von TRUE: 581000 Anzahl von FALSE: 12
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 581000 Anzahl von FALSE: 12
100.0 % der Werte sind TRUE

KDDCup Datensatz

Vergleich von Scores
Anzahl von TRUE: 493345 Anzahl von FALSE: 676
99.86 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 493872 Anzahl von FALSE: 149
99.97 % der Werte sind TRUE

p =  1.7

Iris Datensatz

Vergleich von Scores
Anzahl von TRUE: 150 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 150 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Example2D Datensatz

Vergleich von Scores
Anzahl von TRUE: 175 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 175 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Webspam Datensatz

Vergleich von Scores
Anzahl von TRUE: 349914 Anzahl von FALSE: 86
99.98 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 349999 Anzahl von FALSE: 1
100.0 % der Werte sind TRUE

Covertype Datensatz

Vergleich von Scores
Anzahl von TRUE: 580998 Anzahl von FALSE: 14
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 580998 Anzahl von FALSE: 14
100.0 % der Werte sind TRUE

KDDCup Datensatz

Vergleich von Scores
Anzahl von TRUE: 493990 Anzahl von FALSE: 31
99.99 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 494021 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

p =  2.0

Iris Datensatz

Vergleich von Scores
Anzahl von TRUE: 150 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 150 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Example2D Datensatz

Vergleich von Scores
Anzahl von TRUE: 175 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 175 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Webspam Datensatz

Vergleich von Scores
Anzahl von TRUE: 350000 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 350000 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Covertype Datensatz

Vergleich von Scores
Anzahl von TRUE: 581012 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 581012 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

KDDCup Datensatz

Vergleich von Scores
Anzahl von TRUE: 494021 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 494021 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

In [5]:
# Als csv speichern
df_cmp = pd.DataFrame(rows_cmp).sort_values(["dataset", "p"]).reset_index(drop=True)

float_cols = df_cmp.select_dtypes(include=["float"]).columns
df_cmp[float_cols] = df_cmp[float_cols].round(4)

out_csv = "Tabellen/Vergleich_minmax_l2lp_vs_lewis.csv"
df_cmp.to_csv(out_csv, index=False, float_format="%.4f")
print(f"CSV gespeichert: {out_csv}")

CSV gespeichert: Tabellen/Vergleich_minmax_l2lp_vs_lewis.csv

In [9]:
# Untersuche die maximale Abweichung von lewis zu max(l_ip, l_i2)
# (Wie viel größer ist es maximal von lewis / max(l_ip, l_i2)?)
import numpy as np
import pandas as pd
from efficient_probit_regression.sampling import calculate_lewis_weights_exact, compute_leverage_scores, to_density

# Laden der notwendigen Datensätze
%store -r Iris
%store -r Webspam
%store -r KDDCup
%store -r Covertype
%store -r Example2D

print("Bestimme die maximale Abweichung von lewis zu max(l_ip, l_i2):")
print("")

p = [1.0, 1.3, 1.5, 1.7, 2.0]
rows_cmp = []

datasets = {
    "Iris": Iris,
    "Example2D": Example2D,
    "Webspam": Webspam,
    "Covertype": Covertype,
    "KDDCup": KDDCup,
}

def process_dataset(dataset_name, X, p_val, rows_cmp, T=20):
    print(f"{dataset_name} Datensatz")
    print("")

    # l2 und lp leverage scores + Dichten
    l2_scores = compute_leverage_scores(X, p=2.0)
    l2_prob = to_density(l2_scores)

    lp_scores = compute_leverage_scores(X, p=p_val)
    lp_prob = to_density(lp_scores)

    # Lewis weights + Dichte
    lewis_weights = calculate_lewis_weights_exact(X, p=p_val, T=T)
    lewis_prob = to_density(lewis_weights)

    # Vergleich von Scores
    print("Vergleich von Scores")
    max_scores = np.maximum(lp_scores, l2_scores)
    compare_scores = round(max(lewis_weights / max_scores), 4)

    print("lewis / max(l_ip, l_i2) =", compare_scores)
    print("")

    # Vergleich von normierten Verteilungen
    print("Vergleich von normierten Verteilungen")
    max_prob = np.maximum(lp_prob, l2_prob)
    compare_prob = round(max(lewis_prob / max_prob), 4)

    print("lewis / max(l_ip, l_i2) =", compare_prob)
    print("")

    # ---- Speichern ----
    rows_cmp.append({
        "dataset": dataset_name,
        "p": float(p_val),
        "max_scores_ratio": compare_scores,
        "max_prob_ratio": compare_prob,
    })

for p_val in p:
    print("p = ", p_val)
    print("")
    for dataset_name, ds in datasets.items():
        process_dataset(dataset_name, ds.X, p_val, rows_cmp, T=20)

Bestimme die maximale Abweichung von lewis zu max(l_ip, l_i2):

p =  1.0

Iris Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 1.9067

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 1.6269

Example2D Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 1.6632

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 1.6611

Webspam Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 5.1916

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 5.0288

Covertype Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 33.9124

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 34.3421

KDDCup Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 6.4054

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 3.4369

p =  1.3

Iris Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 1.564

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 1.564

Example2D Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 1.4204

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 1.4204

Webspam Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 6.8668

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 4.1935

Covertype Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 12.3224

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 12.4354

KDDCup Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 5.7447

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 3.4101

p =  1.5

Iris Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 1.3738

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 1.3738

Example2D Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 1.2814

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 1.2814

Webspam Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 4.5312

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 3.5989

Covertype Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 143.7859

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 144.485

KDDCup Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 3.4293

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 3.3642

p =  1.7

Iris Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 1.2098

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 1.2098

Example2D Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 1.1587

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 1.1587

Webspam Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 2.4295

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 1.9135

Covertype Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 62.8106

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 63.0622

KDDCup Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 2.1071

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 2.1071

p =  2.0

Iris Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 1.0

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 1.0

Example2D Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 1.0

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 1.0

Webspam Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 1.0

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 1.0

Covertype Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 1.0

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 1.0

KDDCup Datensatz

Vergleich von Scores
lewis / max(l_ip, l_i2) = 1.0

Vergleich von normierten Verteilungen
lewis / max(l_ip, l_i2) = 1.0

In [10]:
# Als csv speichern
df_cmp = pd.DataFrame(rows_cmp).sort_values(["dataset", "p"]).reset_index(drop=True)

float_cols = df_cmp.select_dtypes(include=["float"]).columns
df_cmp[float_cols] = df_cmp[float_cols].round(4)

out_csv = "Tabellen/Maximale_Abweichung_lewis_max(l2,lp).csv"
df_cmp.to_csv(out_csv, index=False, float_format="%.4f")
print(f"CSV gespeichert: {out_csv}")

CSV gespeichert: Tabellen/Maximale_Abweichung_lewis_max(l2,lp).csv

In [11]:
# Bestimmung von c = max(lewis_prob / l2_lp_prob)
from efficient_probit_regression.sampling import calculate_lewis_weights_exact, calculate_l2_lp_leverage_score, to_density

# 1. Laden der notwendigen Datensätze
%store -r Iris
%store -r Webspam
%store -r KDDCup
%store -r Covertype
%store -r Example2D

print("Bestimmung von c = max(lewis_prob / l2_lp_prob)")
print("")

#Untersuchung für unterschiedliche Werte von p
p = [1.0, 1.3, 1.5, 1.7, 2.0]
rows_c = [] # hier sammeln wir alle Ergebnisse (dataset, p, c)

for i in p:
    print("p = ", i)
    print("")

    #Iris Datensatz
    print("Iris Datensatz")
    Iris_lewis_weights = calculate_lewis_weights_exact(Iris.X, p=i, T=20)
    Iris_lewis_prob = to_density(Iris_lewis_weights)
    Iris_l2_lp_scores = calculate_l2_lp_leverage_score(Iris.X, p=i)[0]
    Iris_l2_lp_prob = calculate_l2_lp_leverage_score(Iris.X, p=i)[1]
    Iris_c = max(Iris_lewis_prob / Iris_l2_lp_prob)
    print("Iris_c:", Iris_c)
    rows_c.append({
        "dataset": "Iris",
        "p": float(i),
        "c": float(Iris_c),
    })
    print("")

    #Example2D Datensatz
    print("Example2D Datensatz")
    Example2D_lewis_weights = calculate_lewis_weights_exact(Example2D.X, p=i, T=20)
    Example2D_lewis_prob = to_density(Example2D_lewis_weights)
    Example2D_l2_lp_scores = calculate_l2_lp_leverage_score(Example2D.X, p=i)[0]
    Example2D_l2_lp_prob = calculate_l2_lp_leverage_score(Example2D.X, p=i)[1]
    Example2D_c = max(Example2D_lewis_prob / Example2D_l2_lp_prob)
    print("Example2D_c:", Example2D_c)
    rows_c.append({
        "dataset": "Example2D",
        "p": float(i),
        "c": float(Example2D_c),
    })
    print("")

    #KDDCup Datensatz
    print("KDDCup Datensatz")
    KDDCup_lewis_weights = calculate_lewis_weights_exact(KDDCup.X, p=i, T=20)
    KDDCup_lewis_prob = to_density(KDDCup_lewis_weights)
    KDDCup_l2_lp_scores = calculate_l2_lp_leverage_score(KDDCup.X, p=i)[0]
    KDDCup_l2_lp_prob = calculate_l2_lp_leverage_score(KDDCup.X, p=i)[1]
    KDDCup_c = max(KDDCup_lewis_prob / KDDCup_l2_lp_prob)
    print("KDDCup_c:", KDDCup_c)
    rows_c.append({
        "dataset": "KDDCup",
        "p": float(i),
        "c": float(KDDCup_c),
    })
    print("")

    #Covertype Datensatz
    print("Covertype Datensatz")
    Covertype_lewis_weights = calculate_lewis_weights_exact(Covertype.X, p=i, T=20)
    Covertype_lewis_prob = to_density(Covertype_lewis_weights)
    Covertype_l2_lp_scores = calculate_l2_lp_leverage_score(Covertype.X, p=i)[0]
    Covertype_l2_lp_prob = calculate_l2_lp_leverage_score(Covertype.X, p=i)[1]
    Covertype_c = max(Covertype_lewis_prob / Covertype_l2_lp_prob)
    print("Covertype_c:", Covertype_c)
    rows_c.append({
        "dataset": "Covertype",
        "p": float(i),
        "c": float(Covertype_c),
    })
    print("")

    #Webspam Datensatz
    print("Webspam Datensatz")
    Webspam_lewis_weights = calculate_lewis_weights_exact(Webspam.X, p=i, T=20)
    Webspam_lewis_prob = to_density(Webspam_lewis_weights)
    Webspam_l2_lp_scores = calculate_l2_lp_leverage_score(Webspam.X, p=i)[0]
    Webspam_l2_lp_prob = calculate_l2_lp_leverage_score(Webspam.X, p=i)[1]
    Webspam_c = max(Webspam_lewis_prob / Webspam_l2_lp_prob)
    print("Webspam_c:", Webspam_c)
    rows_c.append({
        "dataset": "Webspam",
        "p": float(i),
        "c": float(Webspam_c),
    })
    print("")

Bestimmung von c = max(lewis_prob / l2_lp_prob)

p =  1.0

Iris Datensatz
Iris_c: 1.7569250904628144

Example2D Datensatz
Example2D_c: 1.28325295106988

KDDCup Datensatz
KDDCup_c: 4.07443511876122

Covertype Datensatz
Covertype_c: 30.22349221288665

Webspam Datensatz
Webspam_c: 7.963551648565311

p =  1.3

Iris Datensatz
Iris_c: 1.6379458612196875

Example2D Datensatz
Example2D_c: 1.3833524496621765

KDDCup Datensatz
KDDCup_c: 3.399251354915925

Covertype Datensatz
Covertype_c: 13.68007343963104

Webspam Datensatz
Webspam_c: 5.8334183883449695

p =  1.5

Iris Datensatz
Iris_c: 1.3205845684026285

Example2D Datensatz
Example2D_c: 1.2232641294071225

KDDCup Datensatz
KDDCup_c: 3.188945275524326

Covertype Datensatz
Covertype_c: 143.44281447391828

Webspam Datensatz
Webspam_c: 4.029241062457532

p =  1.7

Iris Datensatz
Iris_c: 1.1599733770721903

Example2D Datensatz
Example2D_c: 1.1225972484710844

KDDCup Datensatz
KDDCup_c: 2.0886698647264343

Covertype Datensatz
Covertype_c: 21.009828074731562

Webspam Datensatz
Webspam_c: 2.411237332193192

p =  2.0

Iris Datensatz
Iris_c: 1.0

Example2D Datensatz
Example2D_c: 1.0

KDDCup Datensatz
KDDCup_c: 1.0

Covertype Datensatz
Covertype_c: 1.0

Webspam Datensatz
Webspam_c: 1.0

In [12]:
import pandas as pd

df_c = pd.DataFrame(rows_c)
df_c["c"] = df_c["c"].round(4)
df_c = df_c.sort_values(["dataset", "p"]).reset_index(drop=True)
display(df_c)

# als CSV speichern
out_csv = ("Tabellen/Bestimmung_c_max.csv")
df_c.to_csv(out_csv, index=False)
print(f"CSV gespeichert: {out_csv}")

      dataset    p         c
0   Covertype  1.0   30.2235
1   Covertype  1.3   13.6801
2   Covertype  1.5  143.4428
3   Covertype  1.7   21.0098
4   Covertype  2.0    1.0000
5   Example2D  1.0    1.2833
6   Example2D  1.3    1.3834
7   Example2D  1.5    1.2233
8   Example2D  1.7    1.1226
9   Example2D  2.0    1.0000
10       Iris  1.0    1.7569
11       Iris  1.3    1.6379
12       Iris  1.5    1.3206
13       Iris  1.7    1.1600
14       Iris  2.0    1.0000
15     KDDCup  1.0    4.0744
16     KDDCup  1.3    3.3993
17     KDDCup  1.5    3.1889
18     KDDCup  1.7    2.0887
19     KDDCup  2.0    1.0000
20    Webspam  1.0    7.9636
21    Webspam  1.3    5.8334
22    Webspam  1.5    4.0292
23    Webspam  1.7    2.4112
24    Webspam  2.0    1.0000

CSV gespeichert: Tabellen/Bestimmung_c_max.csv