In [1]:
import numpy as np
from efficient_probit_regression.sampling import calculate_lewis_weights_exact, compute_leverage_scores, to_density

# Laden der notwendigen Datensaetze
%store -r Iris
%store -r Webspam
%store -r KDDCup
%store -r Covertype
%store -r Example2D

print("Bestimmung von c = max(np.maximum(lewis_prob / scaled_l2_lp_prob, scaled_l2_lp_prob / lewis_prob))")
print("")

p = [2.3, 2.5, 3.0, 3.5, 4.0]
LEWIS_ITERATIONS = 20
EPS = 1e-300
rows_c = []

datasets = {
    "Iris": Iris,
    "Example2D": Example2D,
    "Webspam": Webspam,
    "Covertype": Covertype,
    "KDDCup": KDDCup,
}


def scale_factor_d_p_over_2_minus_1(d: int, p_val: float):
    return float(d ** (p_val / 2.0 - 1.0))


def calculate_scaled_l2_lp_scores(X, p_val):
    d = X.shape[1]
    scale_factor = scale_factor_d_p_over_2_minus_1(d, p_val)
    l2_scores = compute_leverage_scores(X, p=2.0, fast_approx=False)
    lp_scores = compute_leverage_scores(X, p=p_val, fast_approx=False)
    scaled_scores = scale_factor * l2_scores + lp_scores
    scaled_prob = to_density(scaled_scores)
    return scaled_scores, scaled_prob, d, scale_factor


for p_val in p:
    print("p = ", p_val)
    print("")

    for dataset_name, ds in datasets.items():
        print(f"{dataset_name} Datensatz")
        lewis_weights = calculate_lewis_weights_exact(ds.X, p=p_val, T=LEWIS_ITERATIONS)
        lewis_prob = to_density(lewis_weights)
        scaled_scores, scaled_prob, d, scale_factor = calculate_scaled_l2_lp_scores(ds.X, p_val)

        c_value = float(np.max(np.maximum(lewis_prob / np.maximum(scaled_prob, EPS), scaled_prob / np.maximum(lewis_prob, EPS))))
        print("c:", c_value)
        rows_c.append({
            "dataset": dataset_name,
            "p": float(p_val),
            "d": int(d),
            "scale_factor": float(scale_factor),
            "c": float(c_value),
        })
        print("")

Bestimmung von c = max(np.maximum(lewis_prob / scaled_l2_lp_prob, scaled_l2_lp_prob / lewis_prob))

p =  2.3

Iris Datensatz
c: 1.207028215021254

Example2D Datensatz
c: 1.1586448179326796

Webspam Datensatz
c: 2.304970051788473

Covertype Datensatz
c: 62.615982039287225

KDDCup Datensatz
c: 2.086717261880734

p =  2.5

Iris Datensatz
c: 1.372645308946349

Example2D Datensatz
c: 1.2763343623359125

Webspam Datensatz
c: 3.8180802969606535

Covertype Datensatz
c: 578.3220636546915

KDDCup Datensatz
c: 3.235341501577226

p =  3.0

Iris Datensatz
c: 1.8946899816614395

Example2D Datensatz
c: 1.5952135478092349

Webspam Datensatz
c: 10.941407424610402

Covertype Datensatz
c: 2055.236710064572

KDDCup Datensatz
c: 8.069251496159872

p =  3.5

Iris Datensatz
c: 2.623346917228983

Example2D Datensatz
c: 1.9873942733250463

Webspam Datensatz
c: 23.745769043305945

Covertype Datensatz
c: 2096.9813680631123

KDDCup Datensatz
c: 15.23334476668273

p =  4.0

Iris Datensatz
c: 3.6358116494468793

Example2D Datensatz
c: 2.464555068152285

Webspam Datensatz
c: 631.3587230443868

Covertype Datensatz
c: 104818.6909363307

KDDCup Datensatz
c: 1372.2947446125097

In [2]:
import pandas as pd

df_c = pd.DataFrame(rows_c)
df_c[["scale_factor", "c"]] = df_c[["scale_factor", "c"]].round(4)
df_c = df_c.sort_values(["dataset", "p"]).reset_index(drop=True)
display(df_c)

out_csv = "Tabellen/Bestimmung_c_symmetrisch_p_groesser_2.csv"
df_c.to_csv(out_csv, index=False)
print(f"CSV gespeichert: {out_csv}")

      dataset    p    d  scale_factor            c
0   Covertype  2.3   55        1.8241      62.6160
1   Covertype  2.5   55        2.7233     578.3221
2   Covertype  3.0   55        7.4162    2055.2367
3   Covertype  3.5   55       20.1963    2096.9814
4   Covertype  4.0   55       55.0000  104818.6909
5   Example2D  2.3    3        1.1791       1.1586
6   Example2D  2.5    3        1.3161       1.2763
7   Example2D  3.0    3        1.7321       1.5952
8   Example2D  3.5    3        2.2795       1.9874
9   Example2D  4.0    3        3.0000       2.4646
10       Iris  2.3    5        1.2731       1.2070
11       Iris  2.5    5        1.4953       1.3726
12       Iris  3.0    5        2.2361       1.8947
13       Iris  3.5    5        3.3437       2.6233
14       Iris  4.0    5        5.0000       3.6358
15     KDDCup  2.3   34        1.6972       2.0867
16     KDDCup  2.5   34        2.4147       3.2353
17     KDDCup  3.0   34        5.8310       8.0693
18     KDDCup  3.5   34       14.0802      15.2333
19     KDDCup  4.0   34       34.0000    1372.2947
20    Webspam  2.3  129        2.0729       2.3050
21    Webspam  2.5  129        3.3701       3.8181
22    Webspam  3.0  129       11.3578      10.9414
23    Webspam  3.5  129       38.2774      23.7458
24    Webspam  4.0  129      129.0000     631.3587

CSV gespeichert: Tabellen/Bestimmung_c_symmetrisch_p_groesser_2.csv

In [8]:
import numpy as np
import pandas as pd
from efficient_probit_regression.sampling import calculate_lewis_weights_exact, compute_leverage_scores, to_density

# Laden der notwendigen Datensaetze
%store -r Iris
%store -r Webspam
%store -r KDDCup
%store -r Covertype
%store -r Example2D

print("Vergleich von 0.5 * min(d^(p/2-1) * l_2, l_p) <= d^(p/2-1) * lewis <= 2 * max(d^(p/2-1) * l_2, l_p):")
print("")

p = [2.3, 2.5, 3.0, 3.5, 4.0]
LEWIS_ITERATIONS = 20
rows_cmp = []

datasets = {
    "Iris": Iris,
    "Example2D": Example2D,
    "Webspam": Webspam,
    "Covertype": Covertype,
    "KDDCup": KDDCup,
}


def scale_factor_d_p_over_2_minus_1(d: int, p_val: float):
    return float(d ** (p_val / 2.0 - 1.0))


def calculate_scaled_scores(X, p_val):
    d = X.shape[1]
    scale_factor = scale_factor_d_p_over_2_minus_1(d, p_val)
    l2_scores = compute_leverage_scores(X, p=2.0, fast_approx=False)
    lp_scores = compute_leverage_scores(X, p=p_val, fast_approx=False)
    scaled_l2_scores = scale_factor * l2_scores
    l2_prob = to_density(l2_scores)
    lp_prob = to_density(lp_scores)
    return l2_scores, lp_scores, scaled_l2_scores, l2_prob, lp_prob, d, scale_factor


def process_dataset(dataset_name, X, p_val, rows_cmp, T=LEWIS_ITERATIONS):
    print(f"{dataset_name} Datensatz")
    print("")

    l2_scores, lp_scores, scaled_l2_scores, l2_prob, lp_prob, d, scale_factor = calculate_scaled_scores(X, p_val)
    lewis_weights = calculate_lewis_weights_exact(X, p=p_val, T=T)
    scaled_lewis_weights = scale_factor * lewis_weights
    lewis_prob = to_density(lewis_weights)

    print("Vergleich von Scores")
    min_scores = np.minimum(scaled_l2_scores, lp_scores)
    max_scores = np.maximum(scaled_l2_scores, lp_scores)
    compare_scores = (scaled_lewis_weights >= min_scores * 0.5) & (scaled_lewis_weights <= max_scores * 2.0)
    true_scores = int(np.sum(compare_scores))
    false_scores = int(len(compare_scores) - true_scores)
    ratio_true_scores = round(true_scores / len(compare_scores), 4) * 100

    print("Anzahl von TRUE:", true_scores, "Anzahl von FALSE:", false_scores)
    print(ratio_true_scores, "% der Werte sind TRUE")
    print("")

    print("Vergleich von normierten Verteilungen")
    min_prob = np.minimum(l2_prob, lp_prob)
    max_prob = np.maximum(l2_prob, lp_prob)
    compare_prob = (lewis_prob >= min_prob * 0.5) & (lewis_prob <= max_prob * 2.0)
    true_prob = int(np.sum(compare_prob))
    false_prob = int(len(compare_prob) - true_prob)
    ratio_true_prob = round(true_prob / len(compare_prob), 4) * 100

    print("Anzahl von TRUE:", true_prob, "Anzahl von FALSE:", false_prob)
    print(ratio_true_prob, "% der Werte sind TRUE")
    print("")

    rows_cmp.append({
        "dataset": dataset_name,
        "p": float(p_val),
        "d": int(d),
        "scale_factor": float(scale_factor),
        "true_scores": true_scores,
        "false_scores": false_scores,
        "true_scores_percent": ratio_true_scores,
        "true_prob": true_prob,
        "false_prob": false_prob,
        "true_prob_percent": ratio_true_prob,
    })


for p_val in p:
    print("p = ", p_val)
    print("")
    for dataset_name, ds in datasets.items():
        process_dataset(dataset_name, ds.X, p_val, rows_cmp)

Vergleich von 0.5 * min(d^(p/2-1) * l_2, l_p) <= d^(p/2-1) * lewis <= 2 * max(d^(p/2-1) * l_2, l_p):

p =  2.3

Iris Datensatz

Vergleich von Scores
Anzahl von TRUE: 150 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 150 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Example2D Datensatz

Vergleich von Scores
Anzahl von TRUE: 175 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 175 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Webspam Datensatz

Vergleich von Scores
Anzahl von TRUE: 350000 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 349994 Anzahl von FALSE: 6
100.0 % der Werte sind TRUE

Covertype Datensatz

Vergleich von Scores
Anzahl von TRUE: 580989 Anzahl von FALSE: 23
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 580988 Anzahl von FALSE: 24
100.0 % der Werte sind TRUE

KDDCup Datensatz

Vergleich von Scores
Anzahl von TRUE: 494021 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 494015 Anzahl von FALSE: 6
100.0 % der Werte sind TRUE

p =  2.5

Iris Datensatz

Vergleich von Scores
Anzahl von TRUE: 150 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 150 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Example2D Datensatz

Vergleich von Scores
Anzahl von TRUE: 175 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 175 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Webspam Datensatz

Vergleich von Scores
Anzahl von TRUE: 349990 Anzahl von FALSE: 10
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 349954 Anzahl von FALSE: 46
99.99 % der Werte sind TRUE

Covertype Datensatz

Vergleich von Scores
Anzahl von TRUE: 580989 Anzahl von FALSE: 23
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 580990 Anzahl von FALSE: 22
100.0 % der Werte sind TRUE

KDDCup Datensatz

Vergleich von Scores
Anzahl von TRUE: 494021 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 494021 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

p =  3.0

Iris Datensatz

Vergleich von Scores
Anzahl von TRUE: 150 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 150 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Example2D Datensatz

Vergleich von Scores
Anzahl von TRUE: 175 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 175 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Webspam Datensatz

Vergleich von Scores
Anzahl von TRUE: 349657 Anzahl von FALSE: 343
99.9 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 349634 Anzahl von FALSE: 366
99.9 % der Werte sind TRUE

Covertype Datensatz

Vergleich von Scores
Anzahl von TRUE: 580956 Anzahl von FALSE: 56
99.99 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 580963 Anzahl von FALSE: 49
99.99 % der Werte sind TRUE

KDDCup Datensatz

Vergleich von Scores
Anzahl von TRUE: 494014 Anzahl von FALSE: 7
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 493983 Anzahl von FALSE: 38
99.99 % der Werte sind TRUE

p =  3.5

Iris Datensatz

Vergleich von Scores
Anzahl von TRUE: 150 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 150 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Example2D Datensatz

Vergleich von Scores
Anzahl von TRUE: 175 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 175 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Webspam Datensatz

Vergleich von Scores
Anzahl von TRUE: 348712 Anzahl von FALSE: 1288
99.63 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 348806 Anzahl von FALSE: 1194
99.66000000000001 % der Werte sind TRUE

Covertype Datensatz

Vergleich von Scores
Anzahl von TRUE: 580880 Anzahl von FALSE: 132
99.98 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 578107 Anzahl von FALSE: 2905
99.5 % der Werte sind TRUE

KDDCup Datensatz

Vergleich von Scores
Anzahl von TRUE: 493916 Anzahl von FALSE: 105
99.98 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 493942 Anzahl von FALSE: 79
99.98 % der Werte sind TRUE

p =  4.0

Iris Datensatz

Vergleich von Scores
Anzahl von TRUE: 0 Anzahl von FALSE: 150
0.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 150 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Example2D Datensatz

Vergleich von Scores
Anzahl von TRUE: 0 Anzahl von FALSE: 175
0.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 175 Anzahl von FALSE: 0
100.0 % der Werte sind TRUE

Webspam Datensatz

Vergleich von Scores
Anzahl von TRUE: 16 Anzahl von FALSE: 349984
0.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 343527 Anzahl von FALSE: 6473
98.15 % der Werte sind TRUE

Covertype Datensatz

Vergleich von Scores
Anzahl von TRUE: 0 Anzahl von FALSE: 581012
0.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 580399 Anzahl von FALSE: 613
99.89 % der Werte sind TRUE

KDDCup Datensatz

Vergleich von Scores
Anzahl von TRUE: 1 Anzahl von FALSE: 494020
0.0 % der Werte sind TRUE

Vergleich von normierten Verteilungen
Anzahl von TRUE: 213685 Anzahl von FALSE: 280336
43.25 % der Werte sind TRUE

In [9]:
df_cmp = pd.DataFrame(rows_cmp).sort_values(["dataset", "p"]).reset_index(drop=True)

float_cols = df_cmp.select_dtypes(include=["float"]).columns
df_cmp[float_cols] = df_cmp[float_cols].round(4)

display(df_cmp)

out_csv = "Tabellen/Vergleich_minmax_l2_lp_vs_lewis_p_groesser_2.csv"
df_cmp.to_csv(out_csv, index=False, float_format="%.4f")
print(f"CSV gespeichert: {out_csv}")

,dataset,p,d,scale_factor,true_scores,false_scores,true_scores_percent,true_prob,false_prob,true_prob_percent
0,Covertype,2.3,55,1.8241,580989,23,100.00,580988,24,100.00
1,Covertype,2.5,55,2.7233,580989,23,100.00,580990,22,100.00
2,Covertype,3.0,55,7.4162,580956,56,99.99,580963,49,99.99
3,Covertype,3.5,55,20.1963,580880,132,99.98,578107,2905,99.50
4,Covertype,4.0,55,55.0000,0,581012,0.00,580399,613,99.89
5,Example2D,2.3,3,1.1791,175,0,100.00,175,0,100.00
6,Example2D,2.5,3,1.3161,175,0,100.00,175,0,100.00
7,Example2D,3.0,3,1.7321,175,0,100.00,175,0,100.00
8,Example2D,3.5,3,2.2795,175,0,100.00,175,0,100.00
9,Example2D,4.0,3,3.0000,0,175,0.00,175,0,100.00
10,Iris,2.3,5,1.2731,150,0,100.00,150,0,100.00
11,Iris,2.5,5,1.4953,150,0,100.00,150,0,100.00
12,Iris,3.0,5,2.2361,150,0,100.00,150,0,100.00
13,Iris,3.5,5,3.3437,150,0,100.00,150,0,100.00
14,Iris,4.0,5,5.0000,0,150,0.00,150,0,100.00
15,KDDCup,2.3,34,1.6972,494021,0,100.00,494015,6,100.00
16,KDDCup,2.5,34,2.4147,494021,0,100.00,494021,0,100.00
17,KDDCup,3.0,34,5.8310,494014,7,100.00,493983,38,99.99
18,KDDCup,3.5,34,14.0802,493916,105,99.98,493942,79,99.98
19,KDDCup,4.0,34,34.0000,1,494020,0.00,213685,280336,43.25
20,Webspam,2.3,129,2.0729,350000,0,100.00,349994,6,100.00
21,Webspam,2.5,129,3.3701,349990,10,100.00,349954,46,99.99
22,Webspam,3.0,129,11.3578,349657,343,99.90,349634,366,99.90
23,Webspam,3.5,129,38.2774,348712,1288,99.63,348806,1194,99.66
24,Webspam,4.0,129,129.0000,16,349984,0.00,343527,6473,98.15

CSV gespeichert: Tabellen/Vergleich_minmax_l2_lp_vs_lewis_p_groesser_2.csv

In [10]:
# Untersuche die maximale Abweichung von scaled_lewis zu max(scaled_l2, l_p)
import numpy as np
import pandas as pd
from efficient_probit_regression.sampling import calculate_lewis_weights_exact, compute_leverage_scores, to_density

# Laden der notwendigen Datensaetze
%store -r Iris
%store -r Webspam
%store -r KDDCup
%store -r Covertype
%store -r Example2D

print("Bestimme die maximale Abweichung von d^(p/2-1) * lewis zu max(d^(p/2-1) * l_2, l_p):")
print("")

p = [2.3, 2.5, 3.0, 3.5, 4.0]
LEWIS_ITERATIONS = 20
EPS = 1e-300
rows_cmp = []

datasets = {
    "Iris": Iris,
    "Example2D": Example2D,
    "Webspam": Webspam,
    "Covertype": Covertype,
    "KDDCup": KDDCup,
}


def scale_factor_d_p_over_2_minus_1(d: int, p_val: float):
    return float(d ** (p_val / 2.0 - 1.0))


def calculate_scaled_scores(X, p_val):
    d = X.shape[1]
    scale_factor = scale_factor_d_p_over_2_minus_1(d, p_val)
    l2_scores = compute_leverage_scores(X, p=2.0, fast_approx=False)
    lp_scores = compute_leverage_scores(X, p=p_val, fast_approx=False)
    scaled_l2_scores = scale_factor * l2_scores
    l2_prob = to_density(l2_scores)
    lp_prob = to_density(lp_scores)
    return l2_scores, lp_scores, scaled_l2_scores, l2_prob, lp_prob, d, scale_factor


def process_dataset(dataset_name, X, p_val, rows_cmp, T=LEWIS_ITERATIONS):
    print(f"{dataset_name} Datensatz")
    print("")

    l2_scores, lp_scores, scaled_l2_scores, l2_prob, lp_prob, d, scale_factor = calculate_scaled_scores(X, p_val)
    lewis_weights = calculate_lewis_weights_exact(X, p=p_val, T=T)
    scaled_lewis_weights = scale_factor * lewis_weights
    lewis_prob = to_density(lewis_weights)

    print("Vergleich von Scores")
    max_scores = np.maximum(scaled_l2_scores, lp_scores)
    max_scores_ratio = round(float(np.max(scaled_lewis_weights / np.maximum(max_scores, EPS))), 4)
    print("scaled_lewis / max(scaled_l2, l_p) =", max_scores_ratio)
    print("")

    print("Vergleich von normierten Verteilungen")
    max_prob = np.maximum(l2_prob, lp_prob)
    max_prob_ratio = round(float(np.max(lewis_prob / np.maximum(max_prob, EPS))), 4)
    print("lewis_prob / max(l_2_prob, l_p_prob) =", max_prob_ratio)
    print("")

    rows_cmp.append({
        "dataset": dataset_name,
        "p": float(p_val),
        "d": int(d),
        "scale_factor": float(scale_factor),
        "max_scores_ratio": max_scores_ratio,
        "max_prob_ratio": max_prob_ratio,
    })


for p_val in p:
    print("p = ", p_val)
    print("")
    for dataset_name, ds in datasets.items():
        process_dataset(dataset_name, ds.X, p_val, rows_cmp)

Bestimme die maximale Abweichung von d^(p/2-1) * lewis zu max(d^(p/2-1) * l_2, l_p):

p =  2.3

Iris Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 1.122

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 1.1021

Example2D Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 1.1639

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 1.1639

Webspam Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 1.6863

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 1.6863

Covertype Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 80.2697

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 79.2809

KDDCup Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 1.442

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 1.4168

p =  2.5

Iris Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 1.2063

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 1.1774

Example2D Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 1.2792

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 1.1964

Webspam Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 2.3475

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 2.3475

Covertype Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 118.5985

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 115.3715

KDDCup Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 1.8025

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 1.8025

p =  3.0

Iris Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 1.426

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 1.426

Example2D Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 1.5858

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 1.5858

Webspam Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 4.9634

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 4.9634

Covertype Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 743.3805

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 702.8366

KDDCup Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 2.9579

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 2.9579

p =  3.5

Iris Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 1.673

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 1.6563

Example2D Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 1.9368

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 1.6186

Webspam Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 9.3091

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 9.1524

Covertype Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 322.5454

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 273.4841

KDDCup Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 4.5937

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 4.5079

p =  4.0

Iris Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 43.8853

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 1.8938

Example2D Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 89.6086

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 1.6812

Webspam Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 8255.2673

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 19.4061

Covertype Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 1387350755.434

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 51477.9509

KDDCup Datensatz

Vergleich von Scores
scaled_lewis / max(scaled_l2, l_p) = 36198.3545

Vergleich von normierten Verteilungen
lewis_prob / max(l_2_prob, l_p_prob) = 25.4661

In [11]:
df_cmp = pd.DataFrame(rows_cmp).sort_values(["dataset", "p"]).reset_index(drop=True)

float_cols = df_cmp.select_dtypes(include=["float"]).columns
df_cmp[float_cols] = df_cmp[float_cols].round(4)

display(df_cmp)

out_csv = "Tabellen/Maximale_Abweichung_lewis_max_l2_lp_p_groesser_2.csv"
df_cmp.to_csv(out_csv, index=False, float_format="%.4f")
print(f"CSV gespeichert: {out_csv}")

      dataset    p    d  scale_factor  max_scores_ratio  max_prob_ratio
0   Covertype  2.3   55        1.8241      8.026970e+01         79.2809
1   Covertype  2.5   55        2.7233      1.185985e+02        115.3715
2   Covertype  3.0   55        7.4162      7.433805e+02        702.8366
3   Covertype  3.5   55       20.1963      3.225454e+02        273.4841
4   Covertype  4.0   55       55.0000      1.387351e+09      51477.9509
5   Example2D  2.3    3        1.1791      1.163900e+00          1.1639
6   Example2D  2.5    3        1.3161      1.279200e+00          1.1964
7   Example2D  3.0    3        1.7321      1.585800e+00          1.5858
8   Example2D  3.5    3        2.2795      1.936800e+00          1.6186
9   Example2D  4.0    3        3.0000      8.960860e+01          1.6812
10       Iris  2.3    5        1.2731      1.122000e+00          1.1021
11       Iris  2.5    5        1.4953      1.206300e+00          1.1774
12       Iris  3.0    5        2.2361      1.426000e+00          1.4260
13       Iris  3.5    5        3.3437      1.673000e+00          1.6563
14       Iris  4.0    5        5.0000      4.388530e+01          1.8938
15     KDDCup  2.3   34        1.6972      1.442000e+00          1.4168
16     KDDCup  2.5   34        2.4147      1.802500e+00          1.8025
17     KDDCup  3.0   34        5.8310      2.957900e+00          2.9579
18     KDDCup  3.5   34       14.0802      4.593700e+00          4.5079
19     KDDCup  4.0   34       34.0000      3.619835e+04         25.4661
20    Webspam  2.3  129        2.0729      1.686300e+00          1.6863
21    Webspam  2.5  129        3.3701      2.347500e+00          2.3475
22    Webspam  3.0  129       11.3578      4.963400e+00          4.9634
23    Webspam  3.5  129       38.2774      9.309100e+00          9.1524
24    Webspam  4.0  129      129.0000      8.255267e+03         19.4061

CSV gespeichert: Tabellen/Maximale_Abweichung_lewis_max_l2_lp_p_groesser_2.csv

In [12]:
# Bestimmung von c = max(lewis_prob / scaled_l2_lp_prob)
import numpy as np
from efficient_probit_regression.sampling import calculate_lewis_weights_exact, compute_leverage_scores, to_density

# Laden der notwendigen Datensaetze
%store -r Iris
%store -r Webspam
%store -r KDDCup
%store -r Covertype
%store -r Example2D

print("Bestimmung von c = max(lewis_prob / scaled_l2_lp_prob)")
print("")

p = [2.3, 2.5, 3.0, 3.5, 4.0]
LEWIS_ITERATIONS = 20
EPS = 1e-300
rows_c = []

datasets = {
    "Iris": Iris,
    "Example2D": Example2D,
    "Webspam": Webspam,
    "Covertype": Covertype,
    "KDDCup": KDDCup,
}


def scale_factor_d_p_over_2_minus_1(d: int, p_val: float):
    return float(d ** (p_val / 2.0 - 1.0))


def calculate_scaled_l2_lp_scores(X, p_val):
    d = X.shape[1]
    scale_factor = scale_factor_d_p_over_2_minus_1(d, p_val)
    l2_scores = compute_leverage_scores(X, p=2.0, fast_approx=False)
    lp_scores = compute_leverage_scores(X, p=p_val, fast_approx=False)
    scaled_scores = scale_factor * l2_scores + lp_scores
    scaled_prob = to_density(scaled_scores)
    return scaled_scores, scaled_prob, d, scale_factor


for p_val in p:
    print("p = ", p_val)
    print("")

    for dataset_name, ds in datasets.items():
        print(f"{dataset_name} Datensatz")
        lewis_weights = calculate_lewis_weights_exact(ds.X, p=p_val, T=LEWIS_ITERATIONS)
        lewis_prob = to_density(lewis_weights)
        scaled_scores, scaled_prob, d, scale_factor = calculate_scaled_l2_lp_scores(ds.X, p_val)

        c_value = float(np.max(lewis_prob / np.maximum(scaled_prob, EPS)))
        print("c:", c_value)
        rows_c.append({
            "dataset": dataset_name,
            "p": float(p_val),
            "d": int(d),
            "scale_factor": float(scale_factor),
            "c": float(c_value),
        })
        print("")

Bestimmung von c = max(lewis_prob / scaled_l2_lp_prob)

p =  2.3

Iris Datensatz
c: 1.1263906940155335

Example2D Datensatz
c: 1.1663515654139034

Webspam Datensatz
c: 1.6839467371493098

Covertype Datensatz
c: 131.16679864657448

KDDCup Datensatz
c: 1.4379335363464643

p =  2.5

Iris Datensatz
c: 1.207061385055249

Example2D Datensatz
c: 1.2881611735106677

Webspam Datensatz
c: 2.350366959549758

Covertype Datensatz
c: 71.83753642431185

KDDCup Datensatz
c: 1.803280836264973

p =  3.0

Iris Datensatz
c: 1.4266964824683672

Example2D Datensatz
c: 1.5867725410350066

Webspam Datensatz
c: 4.96420749507083

Covertype Datensatz
c: 591.3018945753536

KDDCup Datensatz
c: 2.959174014084868

p =  3.5

Iris Datensatz
c: 1.6562123647164264

Example2D Datensatz
c: 1.9119371825155185

Webspam Datensatz
c: 9.15267615069895

Covertype Datensatz
c: 600.1312853779376

KDDCup Datensatz
c: 4.509024274746808

p =  4.0

Iris Datensatz
c: 1.8937491945352707

Example2D Datensatz
c: 2.258800384615893

Webspam Datensatz
c: 19.40625750636888

Covertype Datensatz
c: 2573.1901199551767

KDDCup Datensatz
c: 25.466063846176187

In [13]:
import pandas as pd

df_c = pd.DataFrame(rows_c)
df_c[["scale_factor", "c"]] = df_c[["scale_factor", "c"]].round(4)
df_c = df_c.sort_values(["dataset", "p"]).reset_index(drop=True)
display(df_c)

out_csv = "Tabellen/Bestimmung_c_max_p_groesser_2.csv"
df_c.to_csv(out_csv, index=False)
print(f"CSV gespeichert: {out_csv}")

      dataset    p    d  scale_factor          c
0   Covertype  2.3   55        1.8241   131.1668
1   Covertype  2.5   55        2.7233    71.8375
2   Covertype  3.0   55        7.4162   591.3019
3   Covertype  3.5   55       20.1963   600.1313
4   Covertype  4.0   55       55.0000  2573.1901
5   Example2D  2.3    3        1.1791     1.1664
6   Example2D  2.5    3        1.3161     1.2882
7   Example2D  3.0    3        1.7321     1.5868
8   Example2D  3.5    3        2.2795     1.9119
9   Example2D  4.0    3        3.0000     2.2588
10       Iris  2.3    5        1.2731     1.1264
11       Iris  2.5    5        1.4953     1.2071
12       Iris  3.0    5        2.2361     1.4267
13       Iris  3.5    5        3.3437     1.6562
14       Iris  4.0    5        5.0000     1.8937
15     KDDCup  2.3   34        1.6972     1.4379
16     KDDCup  2.5   34        2.4147     1.8033
17     KDDCup  3.0   34        5.8310     2.9592
18     KDDCup  3.5   34       14.0802     4.5090
19     KDDCup  4.0   34       34.0000    25.4661
20    Webspam  2.3  129        2.0729     1.6839
21    Webspam  2.5  129        3.3701     2.3504
22    Webspam  3.0  129       11.3578     4.9642
23    Webspam  3.5  129       38.2774     9.1527
24    Webspam  4.0  129      129.0000    19.4063

CSV gespeichert: Tabellen/Bestimmung_c_max_p_groesser_2.csv